services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        OCAML_IMAGE: ocaml/opam:debian-12-ocaml-5.2
    working_dir: /workspace
    volumes:
      - .:/workspace
    init: true

  dev-current:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        OCAML_IMAGE: ocaml/opam:debian-12-ocaml-5.5
    working_dir: /workspace
    volumes:
      - .:/workspace
    init: true
