ARG OCAML_IMAGE=ocaml/opam:debian-12-ocaml-5.2
FROM ${OCAML_IMAGE}

WORKDIR /workspace
COPY --chown=opam:opam temporal.opam dune-project ./
RUN opam install --deps-only --with-test -y . \
    && opam install -y ocamlformat.0.28.1

USER opam
CMD ["opam", "exec", "--", "dune", "build"]
