ARG RUST_IMAGE=rust:1.94-bookworm@sha256:6ae102bdbf528294bc79ad6e1fae682f6f7c2a6e6621506ba959f9685b308a55
ARG OCAML_IMAGE=ocaml/opam:debian-12-ocaml-5.2

FROM ${RUST_IMAGE} AS rust-toolchain
RUN rustup component add clippy rustfmt

FROM ${OCAML_IMAGE}

USER root
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        libprotobuf-dev \
        protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

COPY --from=rust-toolchain /usr/local/cargo /usr/local/cargo
COPY --from=rust-toolchain /usr/local/rustup /usr/local/rustup

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/workspace/_build/cargo-home \
    CARGO_TARGET_DIR=/workspace/_build/rust \
    PATH=/usr/local/cargo/bin:${PATH}

USER opam
WORKDIR /workspace
COPY --chown=opam:opam temporal-sdk.opam dune-project ./
RUN opam install --deps-only --with-test -y .

CMD ["opam", "exec", "--", "dune", "build"]
