(** Driver process for the two-OCaml-binary live acceptance test.

    This executable is a deliberately small, typed harness. It starts the
    fan-out, timer, ordinary-retry, heartbeat-detail/retry, delayed
    asynchronous activity completion, timeout-triggered-retry,
    heartbeat-timeout-triggered-retry, activity-level non-retryable failure,
    retryable parent/child retry, parent/child success, parent/child failure,
    typed signal/condition,
    parent/child cancellation, typed-failure, long-running cancellation, and
    continue-as-new scenarios before waiting for most of them. It then stages
    the timeout-triggered retries after the shorter heartbeat/detail path and
    checks the exact terminal outcomes returned by the public client API. Without
    [TEMPORAL_TWO_BINARY_LIVE=1] the process exits with a distinct status
    instead of accidentally exercising the in-memory [mock://] backend and
    giving a false live-smoke signal. *)

module Client = Temporal.Client
module Error = Temporal.Error
module Definitions = Smoke_definitions

(** Wall-clock process timestamp used only for operator diagnostics.
    Workflow payloads and workflow code never call this helper; the driver is
    an ordinary client process, so a clock adjustment can affect only a
    displayed latency and never Temporal determinism. *)
let elapsed_ms started =
  Float.max 0. ((Unix.gettimeofday () -. started) *. 1_000.)

(** Emits one bounded phase record. The fields are operation metadata only:
    workflow/run identifiers and error kinds identify a server interaction,
    while payload bytes and application results are deliberately omitted. *)
let phase ~operation ?status ?workflow_id ?run_id ?duration_ms () =
  let field name value =
    match value with None -> "" | Some value -> " " ^ name ^ "=" ^ value
  in
  let status = field "status" status in
  let workflow_id = field "workflow_id" workflow_id in
  let run_id = field "run_id" run_id in
  let duration_ms =
    match duration_ms with
    | None -> ""
    | Some value -> Printf.sprintf " duration_ms=%.1f" value
  in
  Printf.eprintf "two-binary phase=%s%s%s%s%s\n%!" operation status workflow_id
    run_id duration_ms

(** Measures one client operation and records both its boundary and typed
    result. Keeping this wrapper at the driver boundary makes a future stalled
    native call visible without changing the public result semantics. *)
let measured operation action =
  let started = Unix.gettimeofday () in
  phase ~operation ~status:"begin" ();
  match action () with
  | Ok _ as result ->
      phase ~operation ~status:"ok" ~duration_ms:(elapsed_ms started) ();
      result
  | Error error as result ->
      phase ~operation ~status:("error:" ^ Error.kind error)
        ~duration_ms:(elapsed_ms started) ();
      result

(** The process-level error path reports one expected [result] failure and
    returns a nonzero exit status; ordinary Temporal failures are never raised
    as uncaught OCaml exceptions. *)
let fail operation error =
  phase ~operation ~status:("error:" ^ Error.kind error) ();
  Printf.eprintf "%s failed (%s): %s\n" operation (Error.kind error)
    (Error.message error);
  1

(** Reads a required environment setting as a typed configuration error. *)
let required_env name =
  match Sys.getenv_opt name with
  | Some value when not (String.equal value "") -> Ok value
  | _ -> Error (Error.defect ~message:(name ^ " must not be empty"))

(** Creates an opaque per-run marker token. It is generated by the ordinary
    driver process, recorded as the workflow input, and never used to make a
    workflow decision other than passing it to the test-only marker activity. *)
let cancellation_token () =
  Printf.sprintf "cancellation-%d-%Ld" (Unix.getpid ())
    (Int64.of_float (Unix.gettimeofday () *. 1_000_000.))

(** Creates the distinct token passed through the signal workflow's readiness
    activity. The driver accepts only this exact marker, so a stale file from a
    previous live run cannot establish that the current run reached its first
    worker task. *)
let signal_condition_token () =
  Printf.sprintf "signal-condition-%d-%Ld" (Unix.getpid ())
    (Int64.of_float (Unix.gettimeofday () *. 1_000_000.))

(** Reads an atomically published marker and checks its complete per-run token.
    A stale marker from an interrupted run therefore cannot satisfy either
    handshake, even before the Makefile's best-effort cleanup runs. *)
let marker_matches path token =
  try
    let expected = token ^ "\n" in
    let channel = open_in_bin path in
    Fun.protect
      ~finally:(fun () -> close_in_noerr channel)
      (fun () ->
        let length = in_channel_length channel in
        (* Reject an unexpectedly large marker before allocating a string from
           it. The activity publishes exactly [token] plus one newline; any
           other size is stale or malformed and cannot satisfy this handshake.
           This keeps the driver bounded even when a previous failed run left
           an unrelated file at the shared marker path. *)
        if length <> String.length expected then false
        else
          let contents = really_input_string channel length in
          String.equal contents expected)
  with _ -> false

(** Waits for a named marker activity to complete before sending the next
    control request. The bounded polling loop is intentionally outside
    workflow code: it is ordinary driver-side synchronization with the shared
    bind mount, and its wall-clock timeout cannot affect replay or command
    determinism. *)
let wait_for_marker ~operation path token =
  let timeout_seconds = 30.0 in
  let poll_seconds = 0.05 in
  let deadline = Unix.gettimeofday () +. timeout_seconds in
  let rec loop () =
    if marker_matches path token then Ok ()
    else
      let remaining = deadline -. Unix.gettimeofday () in
      if remaining <= 0.0 then
        Error
          (Error.defect
             ~message:
               (Printf.sprintf
                  "%s marker did not appear within %.0fs" operation
                  timeout_seconds))
      else begin
        Unix.sleepf (Float.min poll_seconds remaining);
        loop ()
      end
  in
  phase ~operation ~status:"begin" ();
  match loop () with
  | Ok () ->
      phase ~operation ~status:"observed" ();
      Ok ()
  | Error error ->
      phase ~operation ~status:("error:" ^ Error.kind error) ();
      Error error

(** Waits for the long-running workflow's activity marker before sending its
    exact cancellation request. *)
let wait_for_cancellation_ready path token =
  wait_for_marker ~operation:"cancellation_ready_wait" path token

(** Waits for the signal workflow's first worker-side marker before sending the
    typed signal. *)
let wait_for_signal_condition_ready path token =
  wait_for_marker ~operation:"signal_condition_ready_wait" path token

(** Prevents a normal local invocation from connecting to an unintended
    endpoint. The dedicated Compose service sets this gate only for the live
    acceptance run. *)
let require_live_gate () =
  match Sys.getenv_opt "TEMPORAL_TWO_BINARY_LIVE" with
  | Some "1" -> Ok ()
  | _ ->
      Error
        (Error.defect
           ~message:
             "two-binary live acceptance is not enabled; set \
              TEMPORAL_TWO_BINARY_LIVE=1 only in its Compose job")

(** Requires a completed terminal outcome with the expected typed payload. *)
let require_completed operation expected = function
  | Ok (Client.Completed actual) when String.equal actual expected -> Ok ()
  | Ok (Client.Completed actual) ->
      Error
        (Error.defect
           ~message:
             (Printf.sprintf "%s returned unexpected result %S" operation actual))
  | Ok (Client.Failed error)
  | Ok (Client.Cancelled error)
  | Ok (Client.Terminated error)
  | Ok (Client.Timed_out error) ->
      Error
        (Error.defect
           ~message:
             (Printf.sprintf "%s completed with Temporal failure: %s" operation
                (Error.message error)))
  | Ok (Client.Continued_as_new { run_id; _ }) ->
      Error
        (Error.defect
           ~message:
             (Printf.sprintf
                "%s continued as new at run %s; exact-run waiting must not \
                 follow it"
                operation run_id))
  | Error error -> Error error

(** Gives terminal outcomes a safe label for phase logs without inspecting the
    typed result value. In particular, completed payload bytes never enter a
    process log. *)
let terminal_kind = function
  | Client.Completed _ -> "completed"
  | Client.Failed _ -> "failed"
  | Client.Cancelled _ -> "cancelled"
  | Client.Terminated _ -> "terminated"
  | Client.Timed_out _ -> "timed_out"
  | Client.Continued_as_new _ -> "continued_as_new"

(** Requires the live workflow to fail as a non-retryable workflow application
    error. [Error.view] exposes the stable category and retry policy while the
    stable message prefix identifies this fixture's intentional failure without
    depending on extra source or Core failure-info text. *)
let require_non_retryable_failure operation expected_message = function
  | Ok (Client.Failed error) ->
      let view = Error.view error in
      if
        view.category = `Workflow
        && view.non_retryable
        && String.starts_with ~prefix:expected_message view.message
      then Ok ()
      else
        Error
          (Error.defect
             ~message:
               (Printf.sprintf
                  "%s returned an unexpected workflow failure (kind=%s, non_retryable=%b)"
                  operation (Error.kind error) view.non_retryable))
  | Ok outcome ->
      Error
        (Error.defect
           ~message:
             (Printf.sprintf "%s returned terminal outcome %s" operation
                (terminal_kind outcome)))
  | Error error -> Error error

(** Requires a parent workflow to fail because its child returned a terminal,
    non-retryable error. Core decorates the diagnostic with child identity and
    failure-info details, and that wording can vary between Core releases; the
    public client contract is a terminal [Workflow] failure whose retryability
    still reflects the nested application cause. The more specific
    [Child_workflow] category is asserted inside the parent workflow when its
    child future resolves. *)
let require_non_retryable_child_failure operation = function
  | Ok (Client.Failed error) ->
      let view = Error.view error in
      if view.category = `Workflow && view.non_retryable then Ok ()
      else
        Error
          (Error.defect
             ~message:
               (Printf.sprintf
                  "%s returned unexpected child failure metadata (kind=%s, non_retryable=%b)"
                  operation (Error.kind error) view.non_retryable))
  | Ok outcome ->
      Error
        (Error.defect
           ~message:
             (Printf.sprintf "%s returned terminal outcome %s" operation
                (terminal_kind outcome)))
  | Error error -> Error error

(** Requires the exact run to report Temporal's cancellation category after a
    successful cancellation acknowledgement. The assertion deliberately checks
    public metadata rather than Core's full failure-info text: category,
    retryability, and the stable message are the contract callers can safely
    branch on. *)
let require_cancelled operation = function
  | Ok (Client.Cancelled error) ->
      let view = Error.view error in
      if
        view.category = `Cancelled
        && not view.non_retryable
        && String.equal view.message "workflow execution was cancelled"
      then Ok ()
      else
        Error
          (Error.defect
             ~message:
               (Printf.sprintf
                  "%s returned unexpected cancellation metadata (kind=%s, non_retryable=%b)"
                  operation (Error.kind error) view.non_retryable))
  | Ok outcome ->
      Error
        (Error.defect
           ~message:
             (Printf.sprintf "%s returned terminal outcome %s" operation
                (terminal_kind outcome)))
  | Error error -> Error error

(** Sends an exact-run cancellation request and records only its acknowledgement
    metadata. A successful result means Temporal accepted the control request;
    the caller must still wait on the same handle to observe the terminal
    cancellation. *)
let cancel_workflow handle =
  let operation = "cancel:" ^ Client.workflow_id handle in
  let started = Unix.gettimeofday () in
  phase ~operation ~status:"begin" ~workflow_id:(Client.workflow_id handle)
    ~run_id:(Client.run_id handle) ();
  match
    Client.cancel ~request_id:"two-binary-cancel-long-running-1"
      ~reason:"live acceptance requested cancellation" handle
  with
  | Ok () ->
      phase ~operation ~status:"acknowledged"
        ~workflow_id:(Client.workflow_id handle) ~run_id:(Client.run_id handle)
        ~duration_ms:(elapsed_ms started) ();
      Ok ()
  | Error error ->
      phase ~operation ~status:("error:" ^ Error.kind error)
        ~workflow_id:(Client.workflow_id handle) ~run_id:(Client.run_id handle)
        ~duration_ms:(elapsed_ms started) ();
      Error error

(** Sends the typed signal to the exact run returned by [Client.start]. The
    acknowledgement proves only that Temporal accepted the request; the later
    [wait_workflow] assertion proves that the worker delivered it to the
    registered handler and that the suspended condition resumed. *)
let signal_workflow handle =
  let operation = "signal:" ^ Client.workflow_id handle in
  let started = Unix.gettimeofday () in
  phase ~operation ~status:"begin" ~workflow_id:(Client.workflow_id handle)
    ~run_id:(Client.run_id handle) ();
  match
    Client.signal ~request_id:"two-binary-signal-1" handle
      ~signal:Definitions.signal_value ~input:"accepted"
  with
  | Ok () ->
      phase ~operation ~status:"acknowledged"
        ~workflow_id:(Client.workflow_id handle) ~run_id:(Client.run_id handle)
        ~duration_ms:(elapsed_ms started) ();
      Ok ()
  | Error error ->
      phase ~operation ~status:("error:" ^ Error.kind error)
        ~workflow_id:(Client.workflow_id handle) ~run_id:(Client.run_id handle)
        ~duration_ms:(elapsed_ms started) ();
      Error error

(** Starts one workflow and records the server-issued run identity only after
    the typed client has accepted it. *)
let start_workflow client ~workflow ~task_queue ~id ~input =
  let operation = "start:" ^ id in
  let started = Unix.gettimeofday () in
  phase ~operation ~status:"begin" ~workflow_id:id ();
  match
    Client.start client ~workflow ~task_queue ~id ~input ()
  with
  | Ok handle as result ->
      phase ~operation ~status:"accepted" ~workflow_id:(Client.workflow_id handle)
        ~run_id:(Client.run_id handle) ~duration_ms:(elapsed_ms started) ();
      result
  | Error error as result ->
      phase ~operation ~status:("error:" ^ Error.kind error) ~workflow_id:id
        ~duration_ms:(elapsed_ms started) ();
      result

(** Waits for one exact run and logs only its terminal class. The returned
    outcome remains untouched so callers still perform the same exact typed
    assertions as the acceptance test did before instrumentation. *)
let wait_workflow handle =
  let operation = "wait:" ^ Client.workflow_id handle in
  let started = Unix.gettimeofday () in
  phase ~operation ~status:"begin" ~workflow_id:(Client.workflow_id handle)
    ~run_id:(Client.run_id handle) ();
  match Client.wait handle with
  | Ok outcome as result ->
      phase ~operation ~status:(terminal_kind outcome)
        ~workflow_id:(Client.workflow_id handle) ~run_id:(Client.run_id handle)
        ~duration_ms:(elapsed_ms started) ();
      result
  | Error error as result ->
      phase ~operation ~status:("error:" ^ Error.kind error)
        ~workflow_id:(Client.workflow_id handle) ~run_id:(Client.run_id handle)
        ~duration_ms:(elapsed_ms started) ();
      result

(** Waits for the original exact run of a continue-as-new workflow, then
    explicitly reconstructs and waits on the returned successor identity. The
    two waits are intentionally separate: following the successor must never
    be implicit in [Client.wait], because callers may need to inspect or stop
    exactly the run they started. *)
let wait_continued_workflow client ~workflow ~operation handle =
  match wait_workflow handle with
  | Error error -> Error error
  | Ok (Client.Continued_as_new execution) -> (
      phase ~operation ~status:"successor"
        ~workflow_id:execution.workflow_id ~run_id:execution.run_id ();
      match Client.follow client ~workflow execution with
      | Error error -> Error error
      | Ok successor_handle -> wait_workflow successor_handle)
  | Ok outcome ->
      Error
        (Error.defect
           ~message:
             (Printf.sprintf
                "%s did not continue as new (terminal outcome %s)" operation
                (terminal_kind outcome)))

(** Runs every live smoke scenario through only the public client surface. *)
let run () =
  match require_live_gate () with
  | Error error -> Error error
  | Ok () ->
      let open Temporal.Result_syntax in
      let* target_url = required_env "TEMPORAL_ADDRESS" in
      let* namespace = required_env "TEMPORAL_NAMESPACE" in
      let* cancellation_ready_file = Definitions.cancellation_ready_file () in
      let* signal_condition_ready_file =
        Definitions.signal_condition_ready_file ()
      in
      (* This cleanup runs after the worker has advertised readiness and before
         any new workflow starts, so a marker from a previous interrupted run
         cannot satisfy the handshake for this run. *)
      let () =
        Definitions.clear_cancellation_ready_file cancellation_ready_file
      in
      let () =
        Definitions.clear_signal_condition_ready_file signal_condition_ready_file
      in
      let cancellation_token = cancellation_token () in
      let signal_condition_token = signal_condition_token () in
      let* client =
        measured "client_create" (fun () ->
            Client.create ~target_url ~namespace
              ~identity:"ocaml-temporal-two-binary-driver" ())
      in
      let finish result =
        phase ~operation:"client_shutdown" ~status:"begin" ();
        let started = Unix.gettimeofday () in
        match Client.shutdown client with
        | Ok () ->
            phase ~operation:"client_shutdown" ~status:"ok"
              ~duration_ms:(elapsed_ms started) ();
            Definitions.clear_cancellation_ready_file cancellation_ready_file;
            Definitions.clear_signal_condition_ready_file signal_condition_ready_file;
            result
        | Error shutdown_error ->
            phase ~operation:"client_shutdown"
              ~status:("error:" ^ Error.kind shutdown_error)
              ~duration_ms:(elapsed_ms started) ();
            Definitions.clear_cancellation_ready_file cancellation_ready_file;
            Definitions.clear_signal_condition_ready_file signal_condition_ready_file;
            Error shutdown_error
      in
      let result =
        let* fan_handle =
          start_workflow client ~workflow:Definitions.fan_out
            ~task_queue:Definitions.task_queue ~id:"two-binary-fan-out" ~input:"smoke"
        in
        let* timer_handle =
          start_workflow client ~workflow:Definitions.timer_then_activity
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-timer-then-activity" ~input:"smoke"
        in
        let* continue_handle =
          start_workflow client ~workflow:Definitions.continue_as_new
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-continue-as-new" ~input:"first"
        in
        let* retry_handle =
          start_workflow client ~workflow:Definitions.activity_retry
            ~task_queue:Definitions.task_queue ~id:"two-binary-activity-retry"
            ~input:"smoke"
        in
        let* heartbeat_retry_handle =
          start_workflow client ~workflow:Definitions.activity_heartbeat_retry
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-activity-heartbeat-retry" ~input:"smoke"
        in
        let* async_completion_handle =
          start_workflow client ~workflow:Definitions.async_activity_completion
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-async-activity-completion" ~input:"smoke"
        in
        let* parent_handle =
          start_workflow client ~workflow:Definitions.parent_awaits_child
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-parent-awaits-child" ~input:"smoke"
        in
        let* failed_child_handle =
          start_workflow client ~workflow:Definitions.parent_awaits_failed_child
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-parent-awaits-failed-child" ~input:"smoke"
        in
        let* cancelled_child_handle =
          start_workflow client ~workflow:Definitions.parent_cancels_child
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-parent-cancels-child" ~input:"smoke"
        in
        let* failure_handle =
          start_workflow client ~workflow:Definitions.non_retryable_failure
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-non-retryable-failure" ~input:"smoke"
        in
        let* activity_non_retryable_handle =
          start_workflow client
            ~workflow:Definitions.activity_non_retryable_failure
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-activity-non-retryable-failure" ~input:"smoke"
        in
        let* child_retry_handle =
          start_workflow client ~workflow:Definitions.parent_retries_child
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-parent-retries-child" ~input:"smoke"
        in
        let* cancellation_handle =
          start_workflow client ~workflow:Definitions.long_running_cancellation
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-long-running-cancellation" ~input:cancellation_token
        in
        let* signal_handle =
          start_workflow client ~workflow:Definitions.signal_condition_workflow
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-signal-condition" ~input:signal_condition_token
        in
        (* Fourteen starts intentionally happen before the first wait. The
           cancellation workflow's marker activity proves that its timer and
           marker commands were accepted in one activation before this exact
           run is cancelled; the timer keeps the execution outstanding. The
           heartbeat workflow is also already outstanding here, so its retry
           runs concurrently with the other live server work instead of being
           mistaken for a sequential local callback. The timeout workflow is
           deliberately started only after the heartbeat workflow has reached
           its terminal retry result below. The activity adapter serializes
           polling, user implementations, heartbeats, and completions behind
           one mutex; starting a six-second timeout callback while a 500ms
           heartbeat lease is outstanding would therefore make this fixture
           test an artificial local queue timeout instead of Temporal's retry
           behavior. The asynchronous activity workflow is also started before
           the first wait; its activity callback returns a deferred handoff and
           the driver later waits for the separate OCaml-owned Domain to complete
           it through the namespace-bound client path. The two child-focused
           parents are likewise started before any wait: one propagates a
           terminal child failure and the other
           waits for Core's child cancellation acknowledgement. The retryable
           child workflow is also already started, so its eventual second
           activity marker is evidence of a server-owned child retry rather
           than a local parent loop. The continuation is also already started,
           so its successor wait is an explicit client operation rather than a
           latest-run lookup. The signal workflow's
           first activity publishes a per-run worker marker; the driver waits
           for that marker before sending the signal, so the request cannot be
           accepted before the worker has taken the execution's first task. *)
        let* () =
          wait_for_signal_condition_ready signal_condition_ready_file
            signal_condition_token
        in
        let* () = signal_workflow signal_handle in
        let* () =
          wait_for_cancellation_ready cancellation_ready_file cancellation_token
        in
        let* () = cancel_workflow cancellation_handle in
        let* fan_result = wait_workflow fan_handle in
        let* () =
          require_completed "smoke.fan_out" "SMOKE:LEFT|SMOKE:RIGHT"
            (Ok fan_result)
        in
        let* timer_result = wait_workflow timer_handle in
        let* () =
          require_completed "smoke.timer_then_activity" "SMOKE:TIMER"
            (Ok timer_result)
        in
        let* continued_result =
          wait_continued_workflow client ~workflow:Definitions.continue_as_new
            ~operation:"smoke.continue_as_new" continue_handle
        in
        let* () =
          require_completed "smoke.continue_as_new" "SMOKE:CONTINUED:SECOND"
            (Ok continued_result)
        in
        let* retry_result = wait_workflow retry_handle in
        let* () =
          require_completed "smoke.activity_retry" "SMOKE:ATTEMPT:2"
            (Ok retry_result)
        in
        let* heartbeat_retry_result = wait_workflow heartbeat_retry_handle in
        let* () =
          require_completed "smoke.activity_heartbeat_retry"
            "SMOKE:HEARTBEAT:RETRIED:SMOKE" (Ok heartbeat_retry_result)
        in
        let* async_completion_result = wait_workflow async_completion_handle in
        let* () =
          require_completed "smoke.async_activity_completion"
            "SMOKE:ASYNC:COMPLETED:SMOKE" (Ok async_completion_result)
        in
        (* Start the intentionally late timeout attempt only after the short
           heartbeat lease has been fully exercised. This preserves the
           single-threaded activity adapter's safety invariant while still
           proving that a late completion is rejected and the Temporal retry
           is dispatched and observed. *)
        let* timeout_retry_handle =
          start_workflow client ~workflow:Definitions.activity_timeout_retry
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-activity-timeout-retry" ~input:"smoke"
        in
        let* timeout_retry_result = wait_workflow timeout_retry_handle in
        let* () =
          require_completed "smoke.activity_timeout_retry"
            "SMOKE:TIMEOUT:RETRIED:SMOKE" (Ok timeout_retry_result)
        in
        (* Start the heartbeat-timeout scenario only after the start-to-close
           timeout scenario has finished. Both first callbacks deliberately
           remain active for six seconds, and the activity adapter serializes
           callback/completion ownership behind one lane. This sequencing
           keeps the observed retry attributable to Temporal's heartbeat
           timeout rather than to local queueing. *)
        let* heartbeat_timeout_retry_handle =
          start_workflow client
            ~workflow:Definitions.activity_heartbeat_timeout_retry
            ~task_queue:Definitions.task_queue
            ~id:"two-binary-activity-heartbeat-timeout-retry" ~input:"smoke"
        in
        let* heartbeat_timeout_retry_result =
          wait_workflow heartbeat_timeout_retry_handle
        in
        let* () =
          require_completed "smoke.activity_heartbeat_timeout_retry"
            "SMOKE:HEARTBEAT_TIMEOUT:RETRIED:SMOKE"
            (Ok heartbeat_timeout_retry_result)
        in
        let* activity_non_retryable_result =
          wait_workflow activity_non_retryable_handle
        in
        let* () =
          require_completed "smoke.activity_non_retryable_failure"
            "SMOKE:ACTIVITY_NON_RETRYABLE:OBSERVED"
            (Ok activity_non_retryable_result)
        in
        let* child_retry_result = wait_workflow child_retry_handle in
        let* () =
          require_completed "smoke.parent_retries_child"
            "SMOKE:CHILD_RETRY:ATTEMPT:2" (Ok child_retry_result)
        in
        let* parent_result = wait_workflow parent_handle in
        let* () =
          require_completed "smoke.parent_awaits_child" "SMOKE:CHILD"
            (Ok parent_result)
        in
        let* failed_child_result = wait_workflow failed_child_handle in
        let* () =
          require_non_retryable_child_failure
            "smoke.parent_awaits_failed_child" (Ok failed_child_result)
        in
        let* cancelled_child_result = wait_workflow cancelled_child_handle in
        let* () =
          require_completed "smoke.parent_cancels_child" "SMOKE:CHILD:CANCELLED"
            (Ok cancelled_child_result)
        in
        let* failure_result = wait_workflow failure_handle in
        let* () =
          require_non_retryable_failure "smoke.non_retryable_failure"
            "intentional terminal workflow failure" (Ok failure_result)
        in
        let* cancellation_result = wait_workflow cancellation_handle in
        let* () =
          require_cancelled "smoke.long_running_cancellation"
            (Ok cancellation_result)
        in
        let* signal_result = wait_workflow signal_handle in
        require_completed "smoke.signal_condition" "SMOKE:SIGNAL:ACCEPTED"
          (Ok signal_result)
      in
      finish result

(** Reports the final typed result and converts it to a process exit code. *)
let () =
  match run () with
  | Ok () -> Printf.printf "two-binary driver assertions passed\n%!"
  | Error error -> exit (fail "two-binary driver" error)
